### PR TITLE
Closes #403

### LINKED ISSUE #403: RDF::Changeset does not appear to accept patterns for deletes
I am currently trying to port my RDF::KV protocol from Perl to Ruby, and have encountered a problem with `RDF::Changeset`. Namely, I feel I should be able to add a pattern to the _delete_ side of a changeset, like the docs (eventually) say.

`RDF::Changeset` includes `RDF::Mutable`, which is where it gets `#insert` and `#delete` from. This is what the documentation for [`RDF::Mutable#delete`](https://www.rubydoc.info/gems/rdf/RDF/Mutable#delete-instance_method) says:

> Deletes RDF statements from `self`. If any statement contains a [`Query::Variable`](https://www.rubydoc.info/gems/rdf/RDF/Query/Variable), it is considered to be a pattern, and used to query self to find matching statements to delete.

Doing this, however, raises an exception.

This doesn't look like it would be too hard to patch. I can provide one if you have no objections.

### PR DESCRIPTION
**Pull request by doriantaylor**
This patch contains both the missing `query` method for `RDF::Changeset` (which I made protected) , as well as ameliorated behaviour on the part of `RDF::Repository`.

I had originally had the `query` method return just an array as that's all `RDF::Mutable#delete` needs to proceed, but then changed it to return an `RDF::Query` with the partial statement as a single pattern. The other solution would be for `RDF::Changeset` to just go around `RDF::Mutable#delete`.

The separate branch [test-wildcard-changeset contains a test case](https://github.com/doriantaylor/rdf/blob/test-wildcard-changeset/spec/changeset_spec.rb#L77) that will demonstrate the crash scenario. You are right however that without its own modifications, `RDF::Repository` would not correctly apply the partial statement, so in effect this one test case probes both scenarios. I don't know if you want a separate/duplicate test case for that.

### CODE REVIEW

File: lib/rdf/changeset.rb [hunk 1]
```diff
@@ -156,6 +156,12 @@ def delete_statement(statement)
       self.deletes << statement
     end
 
+    # This simply returns its argument as a query in order to trick
+    # {RDF::Mutable#delete} into working.
+    def query stmt
```
Comment (gkellogg) [inline lib/rdf/changeset.rb]: Style in RDF.rb is to use parens for method definitions.

```suggestion
    def query(stmt)
```

**Comment by doriantaylor** [comment]
Unsurprisingly the test blows up all over the place when adding the `it_behaves_like…` business. Should an `RDF::Changeset` even _be_ an `RDF::Mutable`? I mean, it makes sense for its components to be…

**Comment by gkellogg** [comment]
It inherits some behavior from `RDF::Mutable`, but doesn't otherwise correspond to its contract. It would be worth experimenting with removing that include, but `RDF::Mutable` is never designed to work on it's own, but when backed by some mutable dataset, such as `RDF::Repository`, so this could be tested by attaching it to a repository, or implementing some mock.

**Comment by doriantaylor** [comment]
My inclination then is to try disentangling `RDF::Changeset` from `RDF::Mutable` as a separate endeavour…

**Comment by gkellogg** [comment]
Okay, I'll pull this PR if you'll look into disentangling changeset and mutable.
