### PR TITLE
RDF::Changeset is now free of RDF::Mutable/RDF::Writable (Closes #405)

### LINKED ISSUE #405: Should RDF::Changeset even be an RDF::Mutable?
Pursuant to discussion in issues #403 and #404, I am putting up this issue as a marker for work on potentially disentangling `RDF::Changeset` from `RDF::Mutable`, since it fails a number of the mutable tests from `rdf-spec`, and will not pass them without adding a bunch of code whose sole purpose would be to pass tests, and removing other code that had been put there on purpose.

Notwithstanding, the `inserts` and `deletes` _members_ of an `RDF::Changeset` instance may indeed _themselves_ make sense behaving as `RDF::Mutable` objects. As such I propose to explore the optimal configuration for `RDF::Changeset`.

### PR DESCRIPTION
**Pull request by doriantaylor**
I didn't bother with a test for the coercion cause it gets tested implicitly in `Writable` and `Mutable`. Closes #405.

### CODE REVIEW

File: lib/rdf/changeset.rb [hunk 1]
```diff
@@ -98,6 +99,24 @@ def readable?
...
+    #
+    # @return [Boolean]
+    # @see    RDF::Writable#writable?
+    def writable?
+      false
+    end
+
+    ##
+    # Returns +false+ to indicate that this changeset _itself_ is not mutable.
+    #
```
Comment (gkellogg) [inline lib/rdf/changeset.rb]: But, it seems that the Changeset _is_ mutable, as you can add or delete statements to it. It just doesn't implement the `RDF::Mutable` interface. An immutable Changeset would be something that was more frozen.

File: lib/rdf/changeset.rb [hunk 2]
```diff
@@ -111,7 +130,7 @@ def apply(mutable, **options)
     end
 
     ##
-    # @return [Boolean] `true` iff inserts and deletes are both empty
+    # @return [Boolean] +true+ iff inserts and deletes are both empty
```
Comment (gkellogg) [inline lib/rdf/changeset.rb]: Why use `+true+`? It doesn't look like yard interprets this.

File: lib/rdf/util/coercions.rb [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+      #  process_statements(statements) { |value| do_something(value) }
+      #
+      # @param statements [#map] The arbitrary-ish input to be manipulated
+      # @param query [false, true] Whether to call +query+ before the block
+      # @param constant [false, true] Whether to test if the statements
+      #  are constant
+      # @yield [RDF::Statement, RDF::Enumerable] 
+      # @return statements
+      def process_statements(statements, query: false, constant: false, &block)
+        raise ArgumentError, 'expecting a block' unless block_given?
```
Comment (gkellogg) [inline lib/rdf/util/coercions.rb]: Given the usage, perhaps `#coerce_statements` would be more appropriate

File: lib/rdf/util/coercions.rb [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+  module Util
+    module Coercions
+      # This is a provisional module intended to house input
+      # coercions. Currently the only coercion is a statement
+      # preprocessor that is used in e.g. {RDF::Writable#insert} and
+      # {RDF::Mutable#delete}.
+
+      ##
+      # Coerce a set of arguments into {RDF::Statement} objects and then
+      # operate over them with a block.
```
Comment (gkellogg) [inline lib/rdf/util/coercions.rb]: "operate over them" seems a bit generic, when what it actually seems to do is to coerce the input to statements, and yield an iterator over those coerced statements.

File: lib/rdf/changeset.rb (hunk 1 above)
Comment (doriantaylor) [reply lib/rdf/changeset.rb]: Is this an issue with that docstring? I suppose I viewed it as an immutable shell with mutable contents. For instance you can freeze an `Array` or `Hash` and not be able to add or remove elements but you're perfectly free to go in and change the elements themselves. I personally think this is weird and would expect immutable to truly _mean_ immutable but I've only been working with Ruby in any serious way for a couple years and figured that the possibility for an immutable object with mutable contents was just how things were done.

At any rate I am not married to this statement and will be happy to change it.

File: lib/rdf/changeset.rb (hunk 2 above)
Comment (doriantaylor) [reply lib/rdf/changeset.rb]: I see the `.yardopts` in the root directory calls for the use of Markdown. I didn't know you could do this; indeed out of the box, YARD delimits code `+like this+`. That's fine; I'm more than content to change it.

File: lib/rdf/util/coercions.rb (hunk 3 above)
Comment (doriantaylor) [reply lib/rdf/util/coercions.rb]: again not married to any particular terminology

File: lib/rdf/util/coercions.rb (hunk 4 above)
Comment (doriantaylor) [reply lib/rdf/util/coercions.rb]: The original code handed off to either `Writable#insert_statements` or `Mutable#delete_statements`, so I guess what it actually expects is an `RDF::Enumerable` or one or more `RDF::Statement` objects.

File: lib/rdf/changeset.rb (hunk 1 above)
Comment (gkellogg) [reply lib/rdf/changeset.rb]: The question is not about documentation, but if it makes sense for Changeset to always return `#mutable?` as `false`, given that it does, in fact, allow statements to be added or deleted. The question is if returning `true` might imply that it implements the contract of `RDF::Mutable`, which I don't think it necessarily does.

IIRC (@no-reply was central to this), the idea was to separate `Dataset` from `Repository` so that a `Repository` could be considered as being based on an immutable `Dataset` with subsequent changes going through a `Changeset`. This could allow Moments-like chaining of Changesets based on transactions (`RDF::Transaction`) on an underlying Repository. Once a Changeset had been applied, it could conceivably live on as an immutable Changeset, providing for some form of rollback. The `RDF::Mutable#snapshot` interface is there to support this type of thing, but this doesn't seem to rely on Changeset, itself, which seems to be more of a transitional structure to keep track of changes as part of a transaction, which are ultimately applied to an underlying Repository.

Comment (doriantaylor) [reply lib/rdf/changeset.rb]: Empirically speaking, instances of `RDF::Changeset` _are_ "mutable", but the entire purpose of this exercise was to make them _not_ include `RDF::Mutable`. These predicates are here on @no-reply's [suggestion](https://github.com/ruby-rdf/rdf/issues/405#issuecomment-571263205) in #405. They could just as well be removed entirely.

When I made the analogous Perl module [`RDF::KV::Patch`](https://metacpan.org/pod/RDF::KV::Patch), the structure I created was likewise a union of two sets of statements (one of which, the statements to _remove_, permitted wildcards), but it was meaningless to consider them as a unitary bucket of statements, because one set of statements is strictly positive and the other is strictly negative. Indeed, I resorted to awkward method names like `add_this` and `dont_add_this` to add/remove statements to the "add" side, and `remove_this` and `dont_remove_this` to add/remove statements to the "remove" side.

Given that, I believe it would make great sense for the `inserts` and `deletes` _members_ of an `RDF::Changeset` instance to _themselves_ be `RDF::Mutable`, since then they could be manipulated directly, and the `insert` and `delete` methods of `RDF::Changeset` could be made proxies to `inserts.insert` and `deletes.insert`. (This assumes we're going to want to edit the contents of a changeset far less than simply appending to it, which is a safe bet.) The `inserts` side, moreover, can be made an in-memory RDF::Repository, which would also have the benefit of de-duplicating statements. The only question would be what to do about the `deletes` side.

Comment (gkellogg) [reply lib/rdf/changeset.rb]: I don't think we need to spend too much time on mutability of a Changset; if it becomes an issue in the future, we can address it then.

**Comment by gkellogg** [comment]
@doriantaylor please consider adding yourself to CREDITS, and if you think you may be more active in this, or other Ruby RDF repos, I can add you to an appropriate team.

**Comment by doriantaylor** [comment]
Thanks; I actually started using Ruby as my daily driver to use this framework more, as it seems to be the best one of the popular general-purpose interpreted languages. I do intend to come up with a more permanent solution for `Changeset`, but this patch should be okay for now.
